"""add_token_model

Revision ID: 8ee24a8517f9
Revises: aa8f51d12026
Create Date: 2026-05-15 19:04:43.528874

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ee24a8517f9'
down_revision: str | Sequence[str] | None = 'aa8f51d12026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('user_status', sa.Enum('UNKNOWN', 'USER', 'ADMIN', name='user_statuses_enum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_table('wallets',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=26), nullable=False),
    sa.Column('pin_hash', sa.String(length=500), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('wallet_type', sa.Enum('UNKNOWN', 'DEBIT', 'CREDIT', name='wallet_types_enum'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('user_id_index', 'wallets', ['user_id'], unique=False)
    op.create_table('balances',
    sa.Column('balance_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('balance_type', sa.Enum('UNKNOWN', 'REGULAR', 'FOREIGN', name='balance_types_enum'), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index('wallet_id_index', 'balances', ['wallet_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('from_address', sa.String(length=26), nullable=False),
    sa.Column('to_address', sa.String(length=26), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=True),
    sa.Column('transaction_type', sa.Enum('UNKNOWN', 'DEPOSIT', 'WITHDRAW', 'EXCHANGE', 'TRANSFER', name='transaction_types_enum'), nullable=False),
    sa.Column('transaction_status', sa.Enum('UNKNOWN', 'FAILED', 'PENDING', 'SUCCESS', name='transaction_statuses_enum'), nullable=False),
    sa.ForeignKeyConstraint(['from_address'], ['wallets.address'], ),
    sa.ForeignKeyConstraint(['to_address'], ['wallets.address'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('wallet_id_index', table_name='balances')
    op.drop_table('balances')
    op.drop_index('user_id_index', table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
